# Generated by Django 5.2 on 2025-04-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_profile_email_profile_firstname_profile_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.TextField(blank=True),
        ),
    ]
